import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Page from "@/lib/assest/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex realtive flex-col">
        {" "}
        {children}{" "}
        <Page.GradualBlur
          target="page"
          position="bottom"
          height="3rem"
          strength={2.5}
          divCount={2}
          curve="bezier"
          exponential
          opacity={0.5}
          className="z-99"
        />
        <Page.ScrollTop />
      </body>
    </html>
  );
}
